const QUOTES = [
  // 영어 명언
  {q:"The secret of getting ahead is getting started.",a:"Mark Twain",k:"앞서 나가는 비결은 시작하는 것이다.",lang:"en"},
  {q:"It always seems impossible until it's done.",a:"Nelson Mandela",k:"모든 것은 이루어지기 전까지는 불가능해 보인다.",lang:"en"},
  {q:"Don't watch the clock; do what it does. Keep going.",a:"Sam Levenson",k:"시계를 보지 마라. 시계처럼 행동하라. 계속 나아가라.",lang:"en"},
  {q:"Believe you can and you're halfway there.",a:"Theodore Roosevelt",k:"할 수 있다고 믿는 순간, 이미 절반은 이룬 것이다.",lang:"en"},
  {q:"The only way to do great work is to love what you do.",a:"Steve Jobs",k:"위대한 일을 하는 유일한 방법은 자신이 하는 일을 사랑하는 것이다.",lang:"en"},
  {q:"Success is not final, failure is not fatal.",a:"Winston Churchill",k:"성공이 끝이 아니고, 실패가 치명적인 것도 아니다. 중요한 것은 계속하는 용기다.",lang:"en"},
  {q:"Hard work beats talent when talent doesn't work hard.",a:"Tim Notke",k:"재능이 노력하지 않을 때, 노력은 재능을 이긴다.",lang:"en"},
  {q:"The future belongs to those who believe in the beauty of their dreams.",a:"Eleanor Roosevelt",k:"미래는 자신의 꿈의 아름다움을 믿는 사람들의 것이다.",lang:"en"},
  {q:"You don't have to be great to start, but you have to start to be great.",a:"Zig Ziglar",k:"위대해야 시작할 수 있는 게 아니라, 시작해야 위대해질 수 있다.",lang:"en"},
  {q:"The harder I work, the luckier I get.",a:"Samuel Goldwyn",k:"더 열심히 일할수록, 더 운이 좋아진다.",lang:"en"},
  {q:"Small daily improvements are the key to staggering long-term results.",a:"Robin Sharma",k:"매일의 작은 발전이 놀라운 장기적 결과의 열쇠다.",lang:"en"},
  {q:"Push yourself, because no one else is going to do it for you.",a:"Unknown",k:"스스로를 밀어붙여라. 아무도 당신 대신 해주지 않는다.",lang:"en"},
  {q:"Great things never come from comfort zones.",a:"Unknown",k:"위대한 것은 절대 편안한 곳에서 오지 않는다.",lang:"en"},
  {q:"Success doesn't just find you. You have to go out and get it.",a:"Unknown",k:"성공은 저절로 찾아오지 않는다. 직접 나가서 쟁취해야 한다.",lang:"en"},
  {q:"Don't stop when you're tired. Stop when you're done.",a:"Unknown",k:"지쳤을 때 멈추지 마라. 다 끝났을 때 멈춰라.",lang:"en"},
  {q:"Do something today that your future self will thank you for.",a:"Unknown",k:"미래의 내가 감사할 일을 오늘 하라.",lang:"en"},
  {q:"It's only a bad day, not a bad life.",a:"Unknown",k:"나쁜 하루일 뿐, 나쁜 인생이 아니다.",lang:"en"},
  {q:"Every day is a second chance.",a:"Unknown",k:"매일은 두 번째 기회다.",lang:"en"},
  {q:"Be stronger than your excuses.",a:"Unknown",k:"변명보다 강해져라.",lang:"en"},
  {q:"Strive for progress, not perfection.",a:"Unknown",k:"완벽함이 아닌 발전을 추구하라.",lang:"en"},
  {q:"Be the change you wish to see in the world.",a:"Mahatma Gandhi",k:"세상에서 보고 싶은 변화가 있다면, 당신이 먼저 그 변화가 되어라.",lang:"en"},
  {q:"In the middle of every difficulty lies opportunity.",a:"Albert Einstein",k:"모든 어려움 한가운데에 기회가 있다.",lang:"en"},
  {q:"Winning isn't everything, but wanting to win is.",a:"Vince Lombardi",k:"이기는 것이 전부는 아니지만, 이기고 싶은 마음은 전부다.",lang:"en"},
  {q:"You miss 100% of the shots you don't take.",a:"Wayne Gretzky",k:"시도하지 않은 슛은 100% 빗나간다.",lang:"en"},
  {q:"I have not failed. I've just found 10,000 ways that won't work.",a:"Thomas Edison",k:"나는 실패한 것이 아니다. 작동하지 않는 1만 가지 방법을 찾았을 뿐이다.",lang:"en"},
  {q:"The only impossible journey is the one you never begin.",a:"Tony Robbins",k:"유일하게 불가능한 여정은 시작하지 않는 것이다.",lang:"en"},
  {q:"Life is what happens when you're busy making other plans.",a:"John Lennon",k:"인생은 다른 계획을 세우느라 바쁜 동안 일어나는 것이다.",lang:"en"},
  {q:"You will face many defeats in life, but never let yourself be defeated.",a:"Maya Angelou",k:"삶에서 많은 패배를 맛보겠지만, 절대 스스로 패배하게 두지 마라.",lang:"en"},
  {q:"Life is either a daring adventure or nothing at all.",a:"Helen Keller",k:"인생은 대담한 모험이거나 아무것도 아닌 것이다.",lang:"en"},
  {q:"Many of life's failures are people who did not realize how close they were to success when they gave up.",a:"Thomas Edison",k:"인생의 많은 실패자들은 포기했을 때 성공에 얼마나 가까이 있었는지 몰랐던 사람들이다.",lang:"en"},
  {q:"It does not matter how slowly you go as long as you do not stop.",a:"Confucius",k:"멈추지 않는 한, 얼마나 천천히 가느냐는 중요하지 않다.",lang:"en"},
  {q:"Our greatest glory is not in never falling, but in rising every time we fall.",a:"Confucius",k:"가장 큰 영광은 한 번도 실패하지 않음이 아니라, 실패할 때마다 일어서는 것이다.",lang:"en"},
  {q:"The man who has confidence in himself gains the confidence of others.",a:"Hasidic proverb",k:"자신을 믿는 사람이 다른 사람의 신뢰를 얻는다.",lang:"en"},
  {q:"Knowing is not enough; we must apply. Willing is not enough; we must do.",a:"Goethe",k:"아는 것으로는 충분하지 않다. 적용해야 한다. 원하는 것으로는 충분하지 않다. 행동해야 한다.",lang:"en"},
  {q:"Once you choose hope, anything is possible.",a:"Christopher Reeve",k:"희망을 선택하는 순간, 모든 것이 가능해진다.",lang:"en"},
  {q:"Try to be a rainbow in someone's cloud.",a:"Maya Angelou",k:"누군가의 먹구름 속에서 무지개가 되어주려 노력하라.",lang:"en"},
  {q:"No act of kindness, no matter how small, is ever wasted.",a:"Aesop",k:"아무리 작은 친절도 결코 낭비되지 않는다.",lang:"en"},
  {q:"If you want to lift yourself up, lift up someone else.",a:"Booker T. Washington",k:"스스로를 일으켜 세우고 싶다면, 다른 사람을 먼저 일으켜 세워라.",lang:"en"},
  {q:"Happiness is not something ready-made. It comes from your own actions.",a:"Dalai Lama",k:"행복은 이미 만들어진 것이 아니다. 자신의 행동에서 비롯된다.",lang:"en"},
  {q:"The best time to plant a tree was 20 years ago. The second best time is now.",a:"Chinese Proverb",k:"나무를 심기에 가장 좋은 시간은 20년 전이었다. 두 번째로 좋은 시간은 바로 지금이다.",lang:"en"},
  {q:"An unexamined life is not worth living.",a:"Socrates",k:"성찰하지 않는 삶은 살 가치가 없다.",lang:"en"},
  {q:"Spread love everywhere you go.",a:"Mother Teresa",k:"가는 곳마다 사랑을 퍼뜨려라.",lang:"en"},
  {q:"When you reach the end of your rope, tie a knot in it and hang on.",a:"Franklin D. Roosevelt",k:"밧줄 끝에 다다랐을 때, 매듭을 짓고 버텨라.",lang:"en"},
  {q:"The purpose of our lives is to be happy.",a:"Dalai Lama",k:"우리 삶의 목적은 행복해지는 것이다.",lang:"en"},
  {q:"Get busy living or get busy dying.",a:"Stephen King",k:"살기 위해 바쁘거나, 죽기 위해 바쁘거나.",lang:"en"},
  {q:"You only live once, but if you do it right, once is enough.",a:"Mae West",k:"인생은 한 번뿐이지만, 제대로 산다면 한 번으로 충분하다.",lang:"en"},
  {q:"Be yourself; everyone else is already taken.",a:"Oscar Wilde",k:"너 자신이 되어라. 다른 사람들은 이미 누군가가 되어 있다.",lang:"en"},
  {q:"Two things are infinite: the universe and human stupidity.",a:"Albert Einstein",k:"두 가지는 무한하다. 우주와 인간의 어리석음.",lang:"en"},
  {q:"A room without books is like a body without a soul.",a:"Marcus Tullius Cicero",k:"책 없는 방은 영혼 없는 몸과 같다.",lang:"en"},
  {q:"You've gotta dance like there's nobody watching.",a:"William W. Purkey",k:"아무도 보지 않는 것처럼 춤을 춰라.",lang:"en"},
  {q:"We accept the love we think we deserve.",a:"Stephen Chbosky",k:"우리는 우리가 받을 자격이 있다고 생각하는 사랑을 받아들인다.",lang:"en"},
  {q:"To live is the rarest thing in the world. Most people exist, that is all.",a:"Oscar Wilde",k:"사는 것은 세상에서 가장 희귀한 일이다. 대부분의 사람들은 그저 존재할 뿐이다.",lang:"en"},
  {q:"Darkness cannot drive out darkness; only light can do that.",a:"Martin Luther King Jr.",k:"어둠은 어둠을 몰아낼 수 없다. 오직 빛만이 그럴 수 있다.",lang:"en"},
  {q:"We must accept finite disappointment, but never lose infinite hope.",a:"Martin Luther King Jr.",k:"유한한 실망은 받아들여야 하지만, 무한한 희망은 절대 잃지 마라.",lang:"en"},
  {q:"In three words I can sum up everything I've learned about life: it goes on.",a:"Robert Frost",k:"내가 인생에서 배운 모든 것을 세 단어로 요약할 수 있다. 삶은 계속된다.",lang:"en"},
  {q:"Not all those who wander are lost.",a:"J.R.R. Tolkien",k:"방황하는 모든 이가 길을 잃은 것은 아니다.",lang:"en"},
  {q:"It is never too late to be what you might have been.",a:"George Eliot",k:"될 수 있었던 사람이 되기에 결코 늦지 않았다.",lang:"en"},
  {q:"Logic will get you from A to Z; imagination will get you everywhere.",a:"Albert Einstein",k:"논리는 A에서 Z로 데려다 줄 것이다. 상상력은 어디든 데려다 줄 것이다.",lang:"en"},
  {q:"If you tell the truth, you don't have to remember anything.",a:"Mark Twain",k:"진실을 말하면 아무것도 기억할 필요가 없다.",lang:"en"},
  {q:"A friend is someone who knows all about you and still loves you.",a:"Elbert Hubbard",k:"친구란 당신의 모든 것을 알면서도 여전히 당신을 사랑하는 사람이다.",lang:"en"},
  {q:"I am so clever that sometimes I don't understand a single word of what I am saying.",a:"Oscar Wilde",k:"나는 너무 영리해서 때때로 내가 말하는 것을 한 마디도 이해하지 못한다.",lang:"en"},
  {q:"To the well-organized mind, death is but the next great adventure.",a:"J.K. Rowling",k:"잘 정돈된 마음에게 죽음은 다음 위대한 모험일 뿐이다.",lang:"en"},
  {q:"The world as we have created it is a process of our thinking.",a:"Albert Einstein",k:"우리가 만들어 낸 세상은 우리의 사고 과정이다.",lang:"en"},
  {q:"It is our choices that show what we truly are, far more than our abilities.",a:"J.K. Rowling",k:"우리가 진정 어떤 사람인지는 능력보다 선택에서 훨씬 더 잘 드러난다.",lang:"en"},
  {q:"There are only two ways to live your life. One is as though nothing is a miracle.",a:"Albert Einstein",k:"삶을 사는 방법은 두 가지다. 하나는 아무것도 기적이 아닌 것처럼, 다른 하나는 모든 것이 기적인 것처럼.",lang:"en"},
  {q:"Do what you can, with what you have, where you are.",a:"Theodore Roosevelt",k:"있는 곳에서, 가진 것으로, 할 수 있는 것을 하라.",lang:"en"},
  {q:"If you look at what you have in life, you'll always have more.",a:"Oprah Winfrey",k:"삶에서 가진 것을 바라보면, 항상 더 많이 가지게 된다.",lang:"en"},
  {q:"If you want to know what a man's like, take a good look at how he treats his inferiors.",a:"J.K. Rowling",k:"어떤 사람인지 알고 싶다면, 그가 자신보다 낮은 사람을 어떻게 대하는지 잘 보라.",lang:"en"},
  {q:"The only person you are destined to become is the person you decide to be.",a:"Ralph Waldo Emerson",k:"당신이 될 운명인 유일한 사람은 당신이 되기로 결정한 사람이다.",lang:"en"},
  {q:"Do not go where the path may lead, go instead where there is no path and leave a trail.",a:"Ralph Waldo Emerson",k:"길이 있는 곳으로 가지 말고, 길이 없는 곳으로 가서 흔적을 남겨라.",lang:"en"},
  {q:"Believe in yourself. You are braver than you think.",a:"Unknown",k:"자신을 믿어라. 당신은 생각보다 용감하다.",lang:"en"},
  {q:"Start where you are. Use what you have. Do what you can.",a:"Arthur Ashe",k:"있는 곳에서 시작하라. 가진 것을 사용하라. 할 수 있는 것을 하라.",lang:"en"},
  {q:"The secret of change is to focus all of your energy not on fighting the old, but on building the new.",a:"Socrates",k:"변화의 비결은 모든 에너지를 낡은 것과 싸우는 데 쓰지 않고 새로운 것을 만드는 데 집중하는 것이다.",lang:"en"},
  {q:"Keep your face always toward the sunshine, and shadows will fall behind you.",a:"Walt Whitman",k:"항상 얼굴을 햇빛 쪽으로 향하라. 그러면 그림자는 뒤에 떨어진다.",lang:"en"},
  {q:"Whether you think you can or you think you can't, you're right.",a:"Henry Ford",k:"할 수 있다고 생각하든 할 수 없다고 생각하든, 당신이 옳다.",lang:"en"},
  {q:"Excellence is not a destination; it is a continuous journey that never ends.",a:"Brian Tracy",k:"탁월함은 목적지가 아니다. 결코 끝나지 않는 지속적인 여정이다.",lang:"en"},
  {q:"Change your thoughts and you change your world.",a:"Norman Vincent Peale",k:"생각을 바꾸면 세상이 바뀐다.",lang:"en"},
  {q:"Too many of us are not living our dreams because we are living our fears.",a:"Les Brown",k:"우리 중 너무 많은 사람들이 두려움 속에 살기 때문에 꿈을 살지 못하고 있다.",lang:"en"},
  {q:"If not now, when?",a:"Hillel the Elder",k:"지금이 아니면 언제?",lang:"en"},
  {q:"You are enough. You have enough. You do enough.",a:"Unknown",k:"당신은 충분하다. 당신은 충분히 가졌다. 당신은 충분히 한다.",lang:"en"},
  {q:"Every moment is a fresh beginning.",a:"T.S. Eliot",k:"모든 순간은 새로운 시작이다.",lang:"en"},
  {q:"Nothing is impossible. The word itself says 'I'm possible!'",a:"Audrey Hepburn",k:"불가능한 것은 없다. '불가능'이라는 단어 자체가 '나는 가능하다!'라고 말한다.",lang:"en"},
  {q:"Challenges are what make life interesting and overcoming them is what makes life meaningful.",a:"Joshua J. Marine",k:"도전은 삶을 흥미롭게 만들고, 그것을 극복하는 것이 삶을 의미 있게 만든다.",lang:"en"},
  {q:"Opportunities don't happen. You create them.",a:"Chris Grosser",k:"기회는 저절로 생기지 않는다. 당신이 만드는 것이다.",lang:"en"},
  {q:"Love your family, work super hard, live your passion.",a:"Gary Vaynerchuk",k:"가족을 사랑하고, 열심히 일하고, 열정을 살아라.",lang:"en"},
  {q:"It is not the mountain we conquer, but ourselves.",a:"Edmund Hillary",k:"우리가 정복하는 것은 산이 아니라 우리 자신이다.",lang:"en"},
  {q:"A journey of a thousand miles begins with a single step.",a:"Lao Tzu",k:"천 리 길도 한 걸음부터 시작된다.",lang:"en"},
  {q:"Fall seven times, stand up eight.",a:"Japanese Proverb",k:"일곱 번 넘어지면 여덟 번 일어나라.",lang:"en"},
  {q:"The way to get started is to quit talking and begin doing.",a:"Walt Disney",k:"시작하는 방법은 말을 멈추고 행동을 시작하는 것이다.",lang:"en"},
  {q:"Your time is limited, don't waste it living someone else's life.",a:"Steve Jobs",k:"당신의 시간은 제한되어 있다. 다른 사람의 삶을 살며 낭비하지 마라.",lang:"en"},
  {q:"If you're going through hell, keep going.",a:"Winston Churchill",k:"지옥을 통과하고 있다면, 계속 나아가라.",lang:"en"},
  {q:"We generate fears while we sit. We overcome them by action.",a:"Dr. Henry Link",k:"우리는 앉아 있는 동안 두려움을 만들어낸다. 행동으로 두려움을 극복한다.",lang:"en"},
  {q:"What seems to us as bitter trials are often blessings in disguise.",a:"Oscar Wilde",k:"우리에게 쓴 시련처럼 보이는 것이 종종 변장한 축복이다.",lang:"en"},
  {q:"The secret to getting ahead is getting started.",a:"Mark Twain",k:"앞서 나가는 비결은 시작하는 것이다.",lang:"en"},
  {q:"I find that the harder I work, the more luck I seem to have.",a:"Thomas Jefferson",k:"더 열심히 일할수록, 더 운이 좋아지는 것 같다.",lang:"en"},
  {q:"The starting point of all achievement is desire.",a:"Napoleon Hill",k:"모든 성취의 출발점은 욕망이다.",lang:"en"},
  {q:"Success usually comes to those who are too busy to be looking for it.",a:"Henry David Thoreau",k:"성공은 보통 그것을 찾기에 너무 바쁜 사람들에게 찾아온다.",lang:"en"},
  {q:"All our dreams can come true, if we have the courage to pursue them.",a:"Walt Disney",k:"추구할 용기가 있다면, 우리의 모든 꿈은 이루어질 수 있다.",lang:"en"},
  // 한국어 명언
  {q:"천 리 길도 한 걸음부터.",a:"한국 속담",k:"",lang:"ko"},
  {q:"뜻이 있는 곳에 길이 있다.",a:"한국 속담",k:"",lang:"ko"},
  {q:"시작이 반이다.",a:"한국 속담",k:"",lang:"ko"},
  {q:"고생 끝에 낙이 온다.",a:"한국 속담",k:"",lang:"ko"},
  {q:"열 번 찍어 안 넘어가는 나무 없다.",a:"한국 속담",k:"",lang:"ko"},
  {q:"오늘 할 수 있는 일을 내일로 미루지 마라.",a:"벤자민 프랭클린",k:"",lang:"ko"},
  {q:"포기하지 않는 한 실패는 없다.",a:"작자 미상",k:"",lang:"ko"},
  {q:"지금 이 순간이 남은 인생에서 가장 젊은 때다.",a:"작자 미상",k:"",lang:"ko"},
  {q:"노력은 배신하지 않는다.",a:"작자 미상",k:"",lang:"ko"},
  {q:"남과 비교하지 말고, 어제의 나와 비교하라.",a:"작자 미상",k:"",lang:"ko"},
  {q:"실수를 두려워하는 것이 가장 큰 실수다.",a:"작자 미상",k:"",lang:"ko"},
  {q:"지금 힘든 것은 앞으로 강해질 증거다.",a:"작자 미상",k:"",lang:"ko"},
  {q:"될 때까지 하면 된다.",a:"작자 미상",k:"",lang:"ko"},
  {q:"성공한 사람은 남들이 쉬는 시간에도 배운다.",a:"작자 미상",k:"",lang:"ko"},
  {q:"완벽한 준비가 될 때까지 기다리면 영원히 시작할 수 없다.",a:"작자 미상",k:"",lang:"ko"},
  {q:"오늘의 땀방울이 내일의 성공을 만든다.",a:"작자 미상",k:"",lang:"ko"},
  {q:"모든 전문가는 한때 초보자였다.",a:"작자 미상",k:"",lang:"ko"},
  {q:"내가 지금 힘들다면, 성장하고 있다는 뜻이다.",a:"작자 미상",k:"",lang:"ko"},
  {q:"한 권의 책이 한 사람의 인생을 바꿀 수 있다.",a:"작자 미상",k:"",lang:"ko"},
  {q:"지금 당장 완벽하지 않아도 된다. 오늘보다 나은 내일이면 충분하다.",a:"작자 미상",k:"",lang:"ko"},
  {q:"꿈이 있는 사람은 오늘도 빛난다.",a:"작자 미상",k:"",lang:"ko"},
  {q:"나를 죽이지 못하는 것은 나를 강하게 만든다.",a:"프리드리히 니체",k:"",lang:"ko"},
  {q:"독서는 마음의 양식이다.",a:"키케로",k:"",lang:"ko"},
  {q:"교육은 미래를 위한 가장 강력한 무기다.",a:"넬슨 만델라",k:"",lang:"ko"},
  {q:"젊음은 두 번 오지 않는다. 지금 이 순간을 소중히.",a:"작자 미상",k:"",lang:"ko"},
  {q:"백 번 듣는 것이 한 번 보는 것만 못하고, 백 번 보는 것이 한 번 해보는 것만 못하다.",a:"한서(漢書)",k:"",lang:"ko"},
  {q:"학이시습지 불역열호 — 배우고 때때로 익히면 또한 기쁘지 아니한가.",a:"논어",k:"",lang:"ko"},
  {q:"진인사대천명 — 사람이 할 도리를 다하고 나서 하늘의 뜻을 기다린다.",a:"명심보감",k:"",lang:"ko"},
  {q:"작은 습관이 큰 변화를 만든다.",a:"작자 미상",k:"",lang:"ko"},
  {q:"포기란 단어는 내 사전에 없다.",a:"나폴레옹",k:"",lang:"ko"},
  {q:"당신은 당신이 생각하는 것보다 훨씬 강하다.",a:"작자 미상",k:"",lang:"ko"},
  {q:"성공은 준비된 사람에게 찾아오는 기회다.",a:"작자 미상",k:"",lang:"ko"},
  {q:"꿈꾸는 것을 두려워하지 마라. 꿈꾸지 않는 것을 두려워하라.",a:"작자 미상",k:"",lang:"ko"},
  {q:"나는 내 미래를 만들고 있다. 지금 이 순간에.",a:"작자 미상",k:"",lang:"ko"},
  {q:"행동이 없는 꿈은 단지 꿈일 뿐이다.",a:"작자 미상",k:"",lang:"ko"},
  {q:"인생에서 가장 중요한 것은 지금 이 순간 최선을 다하는 것이다.",a:"작자 미상",k:"",lang:"ko"},
  {q:"결과보다 과정에서 더 많은 것을 얻는다.",a:"작자 미상",k:"",lang:"ko"},
  {q:"매일 조금씩, 결코 멈추지 않는다.",a:"작자 미상",k:"",lang:"ko"},
  {q:"좋은 습관이 좋은 인생을 만든다.",a:"작자 미상",k:"",lang:"ko"},
  {q:"남이 나를 알아주기를 바라기 전에, 내가 먼저 나를 알아야 한다.",a:"공자",k:"",lang:"ko"},
  {q:"길이 끝나는 곳에서 길은 다시 시작된다.",a:"작자 미상",k:"",lang:"ko"},
  {q:"인생의 의미는 자신의 재능을 발견하는 것이다. 삶의 목적은 그것을 나누는 것이다.",a:"파블로 피카소",k:"",lang:"ko"},
  {q:"지식은 힘이다.",a:"프랜시스 베이컨",k:"",lang:"ko"},
  {q:"천재는 1%의 영감과 99%의 노력으로 이루어진다.",a:"토마스 에디슨",k:"",lang:"ko"},
  {q:"오늘 배우지 않으면 내일은 모른다.",a:"작자 미상",k:"",lang:"ko"},
  {q:"실패는 성공의 어머니다.",a:"작자 미상",k:"",lang:"ko"},
  {q:"자신을 이기는 자가 진정한 강자다.",a:"작자 미상",k:"",lang:"ko"},
  {q:"꿈을 향해 나아가는 것, 그 자체가 이미 성공이다.",a:"작자 미상",k:"",lang:"ko"},
  {q:"오늘 하루도 최선을 다했다면, 그것으로 충분하다.",a:"작자 미상",k:"",lang:"ko"},
  {q:"인생은 가까이서 보면 비극이지만, 멀리서 보면 희극이다.",a:"찰리 채플린",k:"",lang:"ko"},
  {q:"네가 할 수 있다고 믿으면 이미 반은 이룬 것이다.",a:"시어도어 루즈벨트",k:"",lang:"ko"},
  {q:"두려움은 꿈을 쫓는 가장 큰 적이다.",a:"작자 미상",k:"",lang:"ko"},
  {q:"한 계단씩 올라가면 언젠가 정상에 다다른다.",a:"작자 미상",k:"",lang:"ko"},
  {q:"배움에는 끝이 없다. 죽을 때까지 배워라.",a:"작자 미상",k:"",lang:"ko"},
  {q:"오늘의 나는 어제의 내 선택이 만들었다.",a:"작자 미상",k:"",lang:"ko"},
  {q:"불가능이란 단어는 어리석은 자의 사전에만 있다.",a:"나폴레옹",k:"",lang:"ko"},
  {q:"강한 자가 이기는 게 아니라, 이기는 자가 강한 것이다.",a:"작자 미상",k:"",lang:"ko"},
  {q:"하루하루를 마지막인 것처럼 살아라.",a:"스티브 잡스",k:"",lang:"ko"},
  {q:"지금 이 순간의 선택이 10년 후의 나를 만든다.",a:"작자 미상",k:"",lang:"ko"},
];
