const QUOTES = [
  // 영어 명언 (해석 포함)
  {q:"The secret of getting ahead is getting started.",a:"Mark Twain",k:"앞서 나가는 비결은 시작하는 것이다.",lang:"en"},
  {q:"It always seems impossible until it's done.",a:"Nelson Mandela",k:"모든 것은 이루어지기 전까지는 불가능해 보인다.",lang:"en"},
  {q:"Don't watch the clock; do what it does. Keep going.",a:"Sam Levenson",k:"시계를 보지 마라. 시계처럼 행동하라. 계속 나아가라.",lang:"en"},
  {q:"You are never too old to set another goal or dream a new dream.",a:"C.S. Lewis",k:"새로운 목표를 세우거나 새로운 꿈을 꾸기에 너무 늦은 나이란 없다.",lang:"en"},
  {q:"Believe you can and you're halfway there.",a:"Theodore Roosevelt",k:"할 수 있다고 믿는 순간, 이미 절반은 이룬 것이다.",lang:"en"},
  {q:"The only way to do great work is to love what you do.",a:"Steve Jobs",k:"위대한 일을 하는 유일한 방법은 자신이 하는 일을 사랑하는 것이다.",lang:"en"},
  {q:"Success is not final, failure is not fatal.",a:"Winston Churchill",k:"성공이 끝이 아니고, 실패가 치명적인 것도 아니다. 중요한 것은 계속하는 용기다.",lang:"en"},
  {q:"Hard work beats talent when talent doesn't work hard.",a:"Tim Notke",k:"재능이 노력하지 않을 때, 노력은 재능을 이긴다.",lang:"en"},
  {q:"Dream big and dare to fail.",a:"Norman Vaughan",k:"크게 꿈꾸고 실패를 두려워하지 마라.",lang:"en"},
  {q:"What you get by achieving your goals is not as important as what you become.",a:"Henry David Thoreau",k:"목표를 달성해서 얻는 것보다, 그 과정에서 어떤 사람이 되느냐가 더 중요하다.",lang:"en"},
  {q:"The future belongs to those who believe in the beauty of their dreams.",a:"Eleanor Roosevelt",k:"미래는 자신의 꿈의 아름다움을 믿는 사람들의 것이다.",lang:"en"},
  {q:"Don't let yesterday take up too much of today.",a:"Will Rogers",k:"어제가 오늘을 너무 많이 차지하게 두지 마라.",lang:"en"},
  {q:"You don't have to be great to start, but you have to start to be great.",a:"Zig Ziglar",k:"위대해야 시작할 수 있는 게 아니라, 시작해야 위대해질 수 있다.",lang:"en"},
  {q:"The harder I work, the luckier I get.",a:"Samuel Goldwyn",k:"더 열심히 일할수록, 더 운이 좋아진다.",lang:"en"},
  {q:"Small daily improvements are the key to staggering long-term results.",a:"Robin Sharma",k:"매일의 작은 발전이 놀라운 장기적 결과의 열쇠다.",lang:"en"},
  {q:"Your limitation—it's only your imagination.",a:"Unknown",k:"당신의 한계는 오직 당신의 상상력뿐이다.",lang:"en"},
  {q:"Push yourself, because no one else is going to do it for you.",a:"Unknown",k:"스스로를 밀어붙여라. 아무도 당신 대신 해주지 않는다.",lang:"en"},
  {q:"Great things never come from comfort zones.",a:"Unknown",k:"위대한 것은 절대 편안한 곳에서 오지 않는다.",lang:"en"},
  {q:"Dream it. Wish it. Do it.",a:"Unknown",k:"꿈꾸고, 바라고, 행동하라.",lang:"en"},
  {q:"Success doesn't just find you. You have to go out and get it.",a:"Unknown",k:"성공은 저절로 찾아오지 않는다. 직접 나가서 쟁취해야 한다.",lang:"en"},
  {q:"The key to success is to focus on goals, not obstacles.",a:"Unknown",k:"성공의 열쇠는 장애물이 아닌 목표에 집중하는 것이다.",lang:"en"},
  {q:"It's going to be hard, but hard is not impossible.",a:"Unknown",k:"힘들 것이다. 하지만 힘든 것이 불가능한 것은 아니다.",lang:"en"},
  {q:"Don't stop when you're tired. Stop when you're done.",a:"Unknown",k:"지쳤을 때 멈추지 마라. 다 끝났을 때 멈춰라.",lang:"en"},
  {q:"Wake up with determination. Go to bed with satisfaction.",a:"Unknown",k:"결단력으로 일어나고, 만족감으로 잠들어라.",lang:"en"},
  {q:"Do something today that your future self will thank you for.",a:"Unknown",k:"미래의 내가 감사할 일을 오늘 하라.",lang:"en"},
  {q:"Little things make big days.",a:"Unknown",k:"작은 것들이 위대한 하루를 만든다.",lang:"en"},
  {q:"It's only a bad day, not a bad life.",a:"Unknown",k:"나쁜 하루일 뿐, 나쁜 인생이 아니다.",lang:"en"},
  {q:"Every day is a second chance.",a:"Unknown",k:"매일은 두 번째 기회다.",lang:"en"},
  {q:"Be stronger than your excuses.",a:"Unknown",k:"변명보다 강해져라.",lang:"en"},
  {q:"You are capable of more than you know.",a:"Unknown",k:"당신은 스스로 아는 것보다 더 많은 것을 해낼 수 있다.",lang:"en"},
  {q:"Strive for progress, not perfection.",a:"Unknown",k:"완벽함이 아닌 발전을 추구하라.",lang:"en"},
  {q:"You are your only limit.",a:"Unknown",k:"당신의 유일한 한계는 당신 자신이다.",lang:"en"},
  {q:"Be the change you wish to see in the world.",a:"Mahatma Gandhi",k:"세상에서 보고 싶은 변화가 있다면, 당신이 먼저 그 변화가 되어라.",lang:"en"},
  {q:"In the middle of every difficulty lies opportunity.",a:"Albert Einstein",k:"모든 어려움 한가운데에 기회가 있다.",lang:"en"},
  {q:"Life is what happens when you're busy making other plans.",a:"John Lennon",k:"인생은 다른 계획을 세우느라 바쁜 동안 일어나는 것이다.",lang:"en"},
  {q:"Spread love everywhere you go.",a:"Mother Teresa",k:"가는 곳마다 사랑을 퍼뜨려라.",lang:"en"},
  {q:"When you reach the end of your rope, tie a knot in it and hang on.",a:"Franklin D. Roosevelt",k:"밧줄 끝에 다다랐을 때, 매듭을 짓고 버텨라.",lang:"en"},
  {q:"Always remember that you are absolutely unique.",a:"Margaret Mead",k:"당신은 절대적으로 유일한 존재임을 항상 기억하라.",lang:"en"},
  {q:"You will face many defeats in life, but never let yourself be defeated.",a:"Maya Angelou",k:"삶에서 많은 패배를 맛보겠지만, 절대 스스로 패배하게 두지 마라.",lang:"en"},
  {q:"Never let the fear of striking out keep you from playing the game.",a:"Babe Ruth",k:"삼진 당할 두려움이 게임에 참여하는 것을 막게 하지 마라.",lang:"en"},
  {q:"Life is either a daring adventure or nothing at all.",a:"Helen Keller",k:"인생은 대담한 모험이거나 아무것도 아닌 것이다.",lang:"en"},
  {q:"Many of life's failures are people who did not realize how close they were to success when they gave up.",a:"Thomas Edison",k:"인생에서 많은 실패자들은 포기했을 때 성공에 얼마나 가까이 있었는지 깨닫지 못한 사람들이다.",lang:"en"},
  {q:"You have brains in your head. You have feet in your shoes. You can steer yourself any direction you choose.",a:"Dr. Seuss",k:"머릿속에 두뇌가 있고, 신발 속에 발이 있다. 원하는 방향으로 스스로 나아갈 수 있다.",lang:"en"},
  {q:"If life were predictable it would cease to be life.",a:"Eleanor Roosevelt",k:"인생이 예측 가능하다면, 그것은 더 이상 삶이 아닐 것이다.",lang:"en"},
  {q:"Winning isn't everything, but wanting to win is.",a:"Vince Lombardi",k:"이기는 것이 전부는 아니지만, 이기고 싶은 마음은 전부다.",lang:"en"},
  {q:"You miss 100% of the shots you don't take.",a:"Wayne Gretzky",k:"시도하지 않은 슛은 100% 빗나간다.",lang:"en"},
  {q:"I have not failed. I've just found 10,000 ways that won't work.",a:"Thomas Edison",k:"나는 실패한 것이 아니다. 작동하지 않는 1만 가지 방법을 찾았을 뿐이다.",lang:"en"},
  {q:"The only impossible journey is the one you never begin.",a:"Tony Robbins",k:"유일하게 불가능한 여정은 시작하지 않는 것이다.",lang:"en"},
  {q:"In this life we cannot do great things. We can only do small things with great love.",a:"Mother Teresa",k:"이 삶에서 우리는 위대한 일을 할 수 없다. 단지 큰 사랑으로 작은 일을 할 수 있을 뿐이다.",lang:"en"},
  {q:"How wonderful it is that nobody need wait a single moment before starting to improve the world.",a:"Anne Frank",k:"아무도 세상을 개선하기 시작하기 위해 단 한 순간도 기다릴 필요가 없다는 것이 얼마나 놀라운 일인가.",lang:"en"},
  // 한국어 명언
  {q:"천 리 길도 한 걸음부터.",a:"한국 속담",k:"",lang:"ko"},
  {q:"뜻이 있는 곳에 길이 있다.",a:"한국 속담",k:"",lang:"ko"},
  {q:"시작이 반이다.",a:"한국 속담",k:"",lang:"ko"},
  {q:"고생 끝에 낙이 온다.",a:"한국 속담",k:"",lang:"ko"},
  {q:"塗山之水 不擇細流 — 태산은 흙 한 줌도 사양하지 않는다.",a:"사기(史記)",k:"작은 것도 소홀히 하지 않을 때 큰 것이 이루어진다.",lang:"ko"},
  {q:"오늘 할 수 있는 일을 내일로 미루지 마라.",a:"벤자민 프랭클린",k:"",lang:"ko"},
  {q:"포기하지 않는 한 실패는 없다.",a:"작자 미상",k:"",lang:"ko"},
  {q:"꿈을 향해 나아가는 것, 그 자체가 이미 성공이다.",a:"작자 미상",k:"",lang:"ko"},
  {q:"지금 이 순간이 남은 인생에서 가장 젊은 때다.",a:"작자 미상",k:"",lang:"ko"},
  {q:"노력은 배신하지 않는다.",a:"작자 미상",k:"",lang:"ko"},
  {q:"남과 비교하지 말고, 어제의 나와 비교하라.",a:"작자 미상",k:"",lang:"ko"},
  {q:"실수를 두려워하는 것이 가장 큰 실수다.",a:"작자 미상",k:"",lang:"ko"},
  {q:"지금 힘든 것은 앞으로 강해질 증거다.",a:"작자 미상",k:"",lang:"ko"},
  {q:"될 때까지 하면 된다.",a:"작자 미상",k:"",lang:"ko"},
  {q:"행동이 없는 꿈은 단지 꿈일 뿐이다.",a:"작자 미상",k:"",lang:"ko"},
  {q:"성공한 사람은 남들이 쉬는 시간에도 배운다.",a:"작자 미상",k:"",lang:"ko"},
  {q:"완벽한 준비가 될 때까지 기다리면 영원히 시작할 수 없다.",a:"작자 미상",k:"",lang:"ko"},
  {q:"오늘의 땀방울이 내일의 성공을 만든다.",a:"작자 미상",k:"",lang:"ko"},
  {q:"모든 전문가는 한때 초보자였다.",a:"작자 미상",k:"",lang:"ko"},
  {q:"내가 지금 힘들다면, 성장하고 있다는 뜻이다.",a:"작자 미상",k:"",lang:"ko"},
  {q:"한 권의 책이 한 사람의 인생을 바꿀 수 있다.",a:"작자 미상",k:"",lang:"ko"},
  {q:"배움에는 끝이 없다.",a:"작자 미상",k:"",lang:"ko"},
  {q:"지금 이 순간 최선을 다하면, 나중에 후회가 없다.",a:"작자 미상",k:"",lang:"ko"},
  {q:"결과보다 과정에서 더 많은 것을 얻는다.",a:"작자 미상",k:"",lang:"ko"},
  {q:"작은 습관이 큰 변화를 만든다.",a:"작자 미상",k:"",lang:"ko"},
  {q:"나를 죽이지 못하는 것은 나를 강하게 만든다.",a:"프리드리히 니체",k:"",lang:"ko"},
  {q:"인생의 의미는 자신의 재능을 발견하는 것이다. 삶의 목적은 그것을 나누는 것이다.",a:"파블로 피카소",k:"",lang:"ko"},
  {q:"독서는 마음의 양식이다.",a:"키케로",k:"",lang:"ko"},
  {q:"교육은 미래를 위한 가장 강력한 무기다.",a:"넬슨 만델라",k:"",lang:"ko"},
  {q:"젊음은 두 번 오지 않는다. 지금 이 순간을 소중히.",a:"작자 미상",k:"",lang:"ko"},
  {q:"남이 나를 알아주기를 바라기 전에, 내가 먼저 나를 알아야 한다.",a:"공자",k:"",lang:"ko"},
  {q:"백 번 듣는 것이 한 번 보는 것만 못하고, 백 번 보는 것이 한 번 해보는 것만 못하다.",a:"한서(漢書)",k:"",lang:"ko"},
  {q:"열 번 찍어 안 넘어가는 나무 없다.",a:"한국 속담",k:"",lang:"ko"},
  {q:"진인사대천명 — 사람이 할 도리를 다하고 나서 하늘의 뜻을 기다린다.",a:"명심보감",k:"",lang:"ko"},
  {q:"학이시습지 불역열호 — 배우고 때때로 익히면 또한 기쁘지 아니한가.",a:"논어",k:"",lang:"ko"},
  {q:"지금 당장 완벽하지 않아도 된다. 오늘보다 나은 내일이면 충분하다.",a:"작자 미상",k:"",lang:"ko"},
  {q:"꿈이 있는 사람은 오늘도 빛난다.",a:"작자 미상",k:"",lang:"ko"},
  {q:"길이 끝나는 곳에서 길은 다시 시작된다.",a:"작자 미상",k:"",lang:"ko"},
  {q:"포기란 단어는 내 사전에 없다.",a:"나폴레옹",k:"",lang:"ko"},
  {q:"당신은 당신이 생각하는 것보다 훨씬 강하다.",a:"작자 미상",k:"",lang:"ko"},
  {q:"성공은 준비된 사람에게 찾아오는 기회다.",a:"작자 미상",k:"",lang:"ko"},
  {q:"매일 조금씩, 결코 멈추지 않는다.",a:"작자 미상",k:"",lang:"ko"},
  {q:"좋은 습관이 좋은 인생을 만든다.",a:"작자 미상",k:"",lang:"ko"},
  {q:"꿈꾸는 것을 두려워하지 마라. 꿈꾸지 않는 것을 두려워하라.",a:"작자 미상",k:"",lang:"ko"},
  {q:"나는 내 미래를 만들고 있다. 지금 이 순간에.",a:"작자 미상",k:"",lang:"ko"},
];
